
name: CI

on:
  push:
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: packed-solutions/pub_core.zip
          solution-folder: solutions/pub_core/src
          solution-type: Both
          
      - uses: actions/upload-artifact@v2
        with:
          name: packed-solutions
          path: packed-solutions
  
      

      
